### ISSUE TITLE
Freedesktop SDK 24.08 will be dropping appstream-compose

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.freedesktop.Sdk.Extension.openjdk#53]
Please remove manual compose or switch to appstreamcli 

See https://docs.flatpak.org/en/latest/extension.html#extension-manifest for the commands

**Comment by tsmock** [comment]
FTR: https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk/blob/65dd5ab35dfeeb82870f37f32de47d213cb881fc/org.freedesktop.Sdk.Extension.openjdk.yaml#L198-L199

I _think_ the following manifest changes will be needed:
```yaml
build-options:
    prefix: $FLATPAK_DEST
    prepend-path: $FLATPAK_DEST/bin
```
With that said, it _may_ also remove the need for the scripts: https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk/blob/65dd5ab35dfeeb82870f37f32de47d213cb881fc/org.freedesktop.Sdk.Extension.openjdk.yaml#L166-L189

I'm not certain. In any case, I'll _probably_ want to wait to remove the scripts until after the next "major" bump (`23.08` -> `24.08`).

@bbhtt: I've got a couple of questions.
* Is `$FLATPAK_DEST` allowable in `build-options`?
* Am I supposed to use `/usr` or `/app` if `$FLATPAK_DEST` isn't allowable?
* For applications using the `add-extensions` config coption, is `version` able to do something like `version: '>21'`, or is it a strict equality check? I _think_ it is the latter, since I _think_ it is using the `runtime-version` which isn't necessarily a semver compatible string.
* For `prepend-path`, is it possible to concat multiple paths, or is it repeatable?

**Comment by bbhtt** [comment]
> FTR:
> 
> https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk/blob/65dd5ab35dfeeb82870f37f32de47d213cb881fc/org.freedesktop.Sdk.Extension.openjdk.yaml#L198-L199


You need to change only this part. Either drop this line and drop `appstream-compose: false` from the top then the thing happens automatically.

If automatic doesn't work, keep them and change it to:

> `appstreamcli compose --components=${FLATPAK_ID} --prefix=/ --origin=${FLATPAK_ID} --result-root=${FLATPAK_DEST} --data-dir=${FLATPAK_DEST}/share/app-info/xmls ${FLATPAK_DEST}` for composing with appstreamcli
